postscript("boxplot-kroAB100-Objective2.eps", horizontal=FALSE, height=8, width=16, pointsize=12)
data1<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/TSP/SingleObjective/eES/kroAB100/objective2.csv")
data2<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/TSP/SingleObjective/gGA/kroAB100/objective2.csv")
data3<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/TSP/MultiObjective/MOEAD/kroAB100/objective2.csv")
data4<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/TSP/MultiObjective/NSGAII/kroAB100/objective2.csv")
data5<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/TSP/MultiObjective/SMSEMOA/kroAB100/objective2.csv")
dataM<-matrix(c(data1,data2,data3,data4,data5), 100)
library("Rlab")
bplot(dataM, space = 0.6, labels = c("eES", "gGA", "MOEAD", "NSGAII", "SMSEMOA"), ylab = "Objective value", main = "TSP - kroAB100 - Objective 2 - 100 rep.")
dev.off()