postscript("boxplot-1B-2KP400-1C-Objective2.eps", horizontal=FALSE, pointsize=16)
data1<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/SingleObjective/eES/1B/2KP400-1C/objective2.csv")
data2<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/SingleObjective/gGA/1B/2KP400-1C/objective2.csv")
data3<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/MOEAD/1B/2KP400-1C/objective2.csv")
data4<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/NSGAII/1B/2KP400-1C/objective2.csv")
data5<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/SMSEMOA/1B/2KP400-1C/objective2.csv")
dataM<-matrix(c(data1,data2,data3,data4,data5), 100)
library("Rlab")
bplot(dataM, space = 0.6, labels = c("eES", "gGA", "MOEAD", "NSGAII", "SMSEMOA"), ylab = "Objective value", main = "KNP - 1B-2KP400-1C - Objective 2 - 100 rep.")
dev.off()