postscript("boxplot-Uncorrelated-K5050W06-Objective2.eps", horizontal=FALSE, pointsize=16)
data1<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/SingleObjective/eES/Uncorrelated/K5050W06/objective2.csv")
data2<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/SingleObjective/gGA/Uncorrelated/K5050W06/objective2.csv")
data3<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/MOEAD/Uncorrelated/K5050W06/objective2.csv")
data4<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/NSGAII/Uncorrelated/K5050W06/objective2.csv")
data5<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/SMSEMOA/Uncorrelated/K5050W06/objective2.csv")
dataM<-matrix(c(data1,data2,data3,data4,data5), 100)
library("Rlab")
bplot(dataM, space = 0.6, labels = c("eES", "gGA", "MOEAD", "NSGAII", "SMSEMOA"), ylab = "Objective value", main = "KNP - Uncorrelated-K5050W06 - Objective 2 - 100 rep.")
dev.off()