postscript("boxplot-WeakCorrelated-W4C50W01-Objective2.eps", horizontal=FALSE, pointsize=16)
data1<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/SingleObjective/eES/WeakCorrelated/W4C50W01/objective2.csv")
data2<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/SingleObjective/gGA/WeakCorrelated/W4C50W01/objective2.csv")
data3<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/MOEAD/WeakCorrelated/W4C50W01/objective2.csv")
data4<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/NSGAII/WeakCorrelated/W4C50W01/objective2.csv")
data5<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/SMSEMOA/WeakCorrelated/W4C50W01/objective2.csv")
dataM<-matrix(c(data1,data2,data3,data4,data5), 100)
library("Rlab")
bplot(dataM, space = 0.6, labels = c("eES", "gGA", "MOEAD", "NSGAII", "SMSEMOA"), ylab = "Objective value", main = "KNP - WeakCorrelated-W4C50W01 - Objective 2 - 100 rep.")
dev.off()