postscript("boxplot-StrCorrelated-S1150W1-Objective1.eps", horizontal=FALSE, height=8, width=16, pointsize=12)
data1<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/SingleObjective/eES/StrCorrelated/S1150W1/objective1.csv")
data2<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/SingleObjective/gGA/StrCorrelated/S1150W1/objective1.csv")
data3<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/MOEAD/StrCorrelated/S1150W1/objective1.csv")
data4<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/NSGAII/StrCorrelated/S1150W1/objective1.csv")
data5<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/KP/MultiObjective/SMSEMOA/StrCorrelated/S1150W1/objective1.csv")
dataM<-matrix(c(data1,data2,data3,data4,data5), 100)
library("Rlab")
bplot(dataM, space = 0.6, labels = c("eES", "gGA", "MOEAD", "NSGAII", "SMSEMOA"), ylab = "Objective value", main = "KP - StrCorrelated-S1150W1 - Objective 1 - 100 rep.")
dev.off()