postscript("boxplot-kroAB500-Objective1.eps", horizontal=FALSE, height=8, width=16, pointsize=12)
data1<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/TSP/SingleObjective/eES/kroAB500/objective1.csv")
data2<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/TSP/SingleObjective/gGA/kroAB500/objective1.csv")
data3<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/TSP/MultiObjective/MOEAD/kroAB500/objective1.csv")
data4<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/TSP/MultiObjective/NSGAII/kroAB500/objective1.csv")
data5<-scan("/home/edusegre/Descargas/SOvsMO/RESULT/TSP/MultiObjective/SMSEMOA/kroAB500/objective1.csv")
dataM<-matrix(c(data1,data2,data3,data4,data5), 100)
library("Rlab")
bplot(dataM, space = 0.6, labels = c("eES", "gGA", "MOEAD", "NSGAII", "SMSEMOA"), ylab = "Objective value", main = "TSP - kroAB500 - Objective 1 - 100 rep.")
dev.off()